"""
Faithful implementation of Algorithm 1 from Ghimire et al. (2023),
"Pronunciation-Aware Syllable Tokenizer for Nepali ASR System" (ICON 2023).

The paper's own Syllable Dataset (SD) was never published, so this runs the
paper's sliding-window lookup against the lexicon generated by SyllableDataset
in nepali_syllabic_tokenizer.py. That makes the two approaches comparable:
same lexicon, different search strategy.

Deviations from the printed algorithm, all noted in README §2:
  - Line 3 reads `while current_win_pos > len(T)` in the paper, which never
    enters the loop; it must be `<`.
  - `current_win_pos` is never initialized in the paper; it starts at 0.
  - No branch is specified for "no candidate is in SD". As printed the position
    never advances and the loop hangs, so a 1-character fallback is added here.
"""

from typing import List

from nepali_syllabic_tokenizer import SyllableDataset

WIN_SIZE = 4  # paper §4.2: "A maximum of 4 characters are used to form the
              # complex syllables so the window size is considered as 4"


def paper_tokenize(S: str, SD: SyllableDataset, win_size: int = WIN_SIZE) -> List[str]:
    """Algorithm 1: sliding-window longest-match against a syllable lexicon."""
    FT: List[str] = []                       # 1  FT = []
    T = list(S)                              # 2  T = ordered list of chars in S
    current_win_pos = 0

    while current_win_pos < len(T):          # 3  (paper prints `>`)
        t_window = T[current_win_pos:current_win_pos + win_size]        # 4

        # 5  ct = all candidates from t_window, each starting at position 0,
        #    longest first -- eq. (2): {C1C2C3C4, C1C2C3, C1C2, C1}
        ct = [''.join(t_window[:n]) for n in range(len(t_window), 0, -1)]

        for ct_cur in ct:                    # 6
            if ct_cur in SD:                 # 7
                current_win_pos += len(ct_cur)   # 8
                FT.append(ct_cur)                # 9
                break                            # 10
        else:
            # Not in the paper; without it the loop cannot terminate.
            FT.append(T[current_win_pos])
            current_win_pos += 1

    return FT                                # 11


def unreachable_syllables(SD: SyllableDataset, win_size: int = WIN_SIZE) -> List[str]:
    """Lexicon entries longer than the window, which can never be matched."""
    return sorted(s for s in SD.get_all_syllables() if len(s) > win_size)


if __name__ == "__main__":
    from nepali_syllabic_tokenizer import NepaliSyllabicTokenizer

    SD = SyllableDataset()
    rule = NepaliSyllabicTokenizer()

    # Figure 1 and Table 3 of the paper
    for s in ["क्षेत्रमा कसैका", "व्यक्तित्वमा प्रभाव पर्ने", "घाउ लागेको क्षेत्रमा", "क्रान्ति"]:
        print(f"{s}\n  {paper_tokenize(s, SD)}")

    # Where window size 4 is too small for the lexicon it searches
    unreachable = unreachable_syllables(SD)
    print(f"\nSD entries unreachable at win_size={WIN_SIZE}: "
          f"{len(unreachable)}/{len(SD)}  e.g. {unreachable[:4]}")
    for s in ["क्षिं", "त्रैं"]:
        print(f"  {s}  paper: {paper_tokenize(s, SD)}   rule-based: {rule.tokenize(s)}")
